version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
