version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: mohirdev-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - mohirdev-docker-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: mohirdev-docker-api
    command: npm run start
    volumes:
      - "./api:/usr/src/app"
      - "node_modules:/usr/src/app/node_modules"
    restart: unless-stopped
    environment:
      - PORT=3001
      - HOST=http://localhost:3001
      - MONGO_URL=mongodb://api_db:27017/api
      - SECRET_KEY=mysecretkey
    depends_on:
      - api_db
    networks:
      - mohirdev-docker-network

  api_db:
    image: mongo:latest
    container_name: mohirdev-docker-api-db
    volumes:
      - mohirdev_mongodb_api:/data/db
    ports:
      - "27017:27017"
    networks:
      - mohirdev-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: mohirdev-docker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - mohirdev-docker-network

volumes:
  mohirdev_mongodb_api:
  node_modules:
networks:
  mohirdev-docker-network:
    driver: bridge
