version: "3"

# Bu yerda barcha servislarimiz bo'ladi
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: mohirdev-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - mohirdev-docker-network # Connect frontend service to the mohirdev-docker-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: mohirdev-docker-api
    command: npm run start # We need this command to run the server inside the container
    restart: unless-stopped
    # ports:
    #   - "3001:3001" # "out_port:in_port"
    environment:
      - PORT=3001
      - HOST=http://localhost:3001
      - MONGO_URL=mongodb://api_db:27017/api
      - SECRET_KEY=mysecretkey
    depends_on:
      - api_db
    networks:
      - mohirdev-docker-network # Connect api service to the mohirdev-docker-network

  api_db:
    image: mongo:latest
    container_name: mohirdev-docker-api-db
    volumes: # https://docs.docker.com/storage/volumes/ Volumes, нам нужно, чтобы необходимые файлы сохранялись по указанным путям, это обеспечит персистентность данных
      - mohirdev_mongodb_api:/data/db # Этот volume добавлен чтобы чтобы после запуска docker контайнеров сохранилось данные
    # ports:
    #   - "27017:27017"
    networks:
      - mohirdev-docker-network # Connect api_db service to the mohirdev-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: mohirdev-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - mohirdev-docker-network # Connect nginx service to the mohirdev-docker-network

volumes:
  mongodb_api: # This volumes is added so that this volume is used between services

networks:
  mohirdev-docker-network: # Create new network with name mohirdev-docker-network
    driver: bridge
