version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Node version
          command: node --version
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor:
      name: node/default
    steps:
      - run:
          name: Print path 1
          command: pwd
      - attach_workspace:
          at: .
      - run:
          name: Print path 2
          command: pwd
      - add_ssh_keys:
          fingerprints:
            - "42:8f:33:18:b5:6b:94:aa:f7:5b:ee:0d:b2:67:af:75"
      - run:
          name: Deploy to development server
          command: |
            ssh $DEPLOY_USER@$DEPLOY_HOST -o StrictHostKeyChecking=no "cd $DEPLOY_PATH && git pull"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
