version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd api && npm install && npm test
      - run: cd frontend && npm install && npm test

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Build api
          command: cd api && npm install && npm build
      - run:
          name: Build frontend
          command: cd frontend && npm install && npm build

  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "42:8f:33:18:b5:6b:94:aa:f7:5b:ee:0d:b2:67:af:75"
      - run:
          name: Deploy to development server
          command: |
            ssh $DEPLOY_USER@$DEPLOY_HOST -o StrictHostKeyChecking=no "cd $DEPLOY_PATH && git pull"

workflows:
  version: 2
  build-deploy:
    jobs:
      - tests
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
